let albums = [
  {
    id: 1,
    artist: 'Sweet Trip',
    title: 'Velocity:Design:Comfort',
    price: 22,
    genre: 'Electronic',
  },
  {
    id: 2,
    artist: 'Burial',
    title: 'Untrue',
    price: 18,
    genre: 'Electronic',
  },
  {
    id: 3,
    artist: 'The Flaming Lips',
    title: 'The Soft Bulletin',
    price: 28,
    genre: 'Indie Rock',
  },
  {
    id: 4,
    artist: 'Radiohead',
    title: 'In Rainbows',
    price: 30,
    genre: 'Alternative',
  },
  {
    id: 5,
    artist: 'OPERATION: DOOMSDAY',
    title: 'MF Doom',
    price: 32,
    genre: 'Rap',
  },
  {
    id: 6,
    artist: 'Beach House',
    title: 'Bloom',
    price: 24,
    genre: 'Alternative',
  },
  {
    id: 7,
    artist: 'Sade',
    title: 'Love Deluxe',
    price: 34,
    genre: 'R&B',
  },
  {
    id: 8,
    artist: 'Kate Bush',
    title: 'Hounds of Love',
    price: 29,
    genre: 'Pop',
  },
  {
    id: 9,
    artist: 'David Bowie',
    title: 'Blackstar',
    price: 35,
    genre: 'Rock',
  },
  {
    id: 10,
    artist: 'FKA twigs',
    title: 'Magdalene',
    price: 28,
    genre: 'Electronic',
  },
  {
    id: 11,
    artist: 'Aphex Twin',
    title: 'Selected Ambient Works 85-92',
    price: 20,
    genre: 'Electronic',
  },
  {
    id: 12,
    artist: 'The Cure',
    title: 'Disintegration',
    price: 20,
    genre: 'Rock',
  },
]

export default albums